### ISSUE TITLE
Compilation error on SUSE and Debian systems

### ISSUE THREAD

**Issue by shabiel** [anet-be/lua-yottadb#25]
```
$ make
gcc yottadb.c callins.c cachearray.c compat-5.3/c-api/compat-5.3.c -o _yottadb.so  -shared -Wl,--version-script=exports.map -g -O3 -fPIC -std=c11 -I/usr/library/V999_R139/dbg -I/usr/include/lua5.3 -pedantic -Wall -Werror -Wextra -Wno-cast-function-type -Wno-unknown-pragmas -Wno-discarded-qualifiers -L/usr/library/V999_R139/dbg -lyottadb -Wl,-rpath,/usr/library/V999_R139/dbg -Wl,--gc-sections
cachearray.c: In function ‘_cachearray_create’:
cachearray.c:128:9: error: implicit declaration of function ‘luai_unlikely’; did you mean ‘luaL_unref’? [-Werror=implicit-function-declaration]
     if (luai_unlikely(!string))
         ^~~~~~~~~~~~~
         luaL_unref
cachearray.c: At top level:
cc1: error: unrecognized command line option ‘-Wno-cast-function-type’ [-Werror]
cc1: all warnings being treated as errors
make: *** [Makefile:34: _yottadb.so] Error 1
```

On Debian Bullseye, Lua is 5.4.2; On Suse SLED 15, it's 5.3.6.

**Comment by berwynhoyt** [comment]
I think this has already been fixed in commit cdd0520. Can you update and try again?

**Comment by berwynhoyt** [comment]
Correction. I have NOW committed this fix in commit [8c7a56d](https://github.com/anet-be/lua-yottadb/commit/8c7a56d9d5630e9b6ae5b9a38135ddd151193439).

**Comment by shabiel** [comment]
I knew from your first message that you didn't fix it yet, but I am glad you figured it out. I was in bed by then :-).
